name: Pull request based flow
on:
  push:
    branches:
      - 'demo/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger on PR event
      run: echo "This is PR based workflow" 